# preload = ~/.config/hypr/wallpaper/clive.jpg
# wallpaper = , ~/.config/hypr/wallpaper/clive.jpg

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper/vivi.jpg
    fit_mode = cover
}

splash = false