# preload = ~/.config/hypr/wallpaper/clive.jpg
# wallpaper = , ~/.config/hypr/wallpaper/clive.jpg

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/wallpaper/chocobokick-0-2048x1024.png
    fit_mode = cover
}

splash = false